In [3]:
import pandas as pd

In [4]:
# Bu alanda ilgili csv dosyasının dosya yolu verilmektedir?
df = pd.read_csv(r"C:\Users\realb\Desktop\ML_dersler\ML_201\Çoklu Doğrusal Regresyon Model/Advertising.csv")
# Bu alanda ise index değerlerini bir değişken gibi okumaının önüne geçilmiştir.
df = df.iloc[:,1:len(df)]
# BU alanda ise csv dosyasının ilk beş değeri ekrana getirilmelidir.
df.head()

TV  radio  newspaper  sales
0  230.1   37.8       69.2   22.1
1   44.5   39.3       45.1   10.4
2   17.2   45.9       69.3    9.3
3  151.5   41.3       58.5   18.5
4  180.8   10.8       58.4   12.9

In [5]:
# şimdi burda bağımsız değişkenleri x diyerek bir değere atamasını yapıyorum.
X = df.drop('sales', axis=1)
# şimdi ise bağımlı değişkeni y diyerek başka bir değere atamasını yapıyorum.
y = df[["sales"]]
# Bu değerlei pandas dataframe olarak almak için çift köşeli parantez olarak almanız gerekmektedir.

In [6]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [7]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [12]:
# İlgili kütüpaneyi import ediyorum.
import statsmodels.api as sm

In [13]:
# Şimdi burda bir değişken tanımlayıp içerden linner regrassyon modelime bağlı fonksyonumu çağırma işlemini yapıyorum.
lm = sm.OLS(y, X)

In [14]:
# Şİmdi ise modeli kuram modeli fit etme işlemini yapıyoruz.
model = lm.fit()

In [15]:
# Bana burda modelin özetlerini ver anlamına gelmektedir.
model.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results                                
=======================================================================================
Dep. Variable:                  sales   R-squared (uncentered):                   0.982
Model:                            OLS   Adj. R-squared (uncentered):              0.982
Method:                 Least Squares   F-statistic:                              3566.
Date:                Mon, 11 Mar 2024   Prob (F-statistic):                   2.43e-171
Time:                        11:38:03   Log-Likelihood:                         -423.54
No. Observations:                 200   AIC:                                      853.1
Df Residuals:                     197   BIC:                                      863.0
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
TV             0.0538      0.001     40.507      0.000       0.051       0.056
radio          0.2222      0.009     23.595      0.000       0.204       0.241
newspaper      0.0168      0.007      2.517      0.013       0.004       0.030
==============================================================================
Omnibus:                        5.982   Durbin-Watson:                   2.038
Prob(Omnibus):                  0.050   Jarque-Bera (JB):                7.039
Skew:                          -0.232   Prob(JB):                       0.0296
Kurtosis:                       3.794   Cond. No.                         12.6
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

# Scikit learn ile model kurma işlemleri

In [17]:
# Kullanmak için modeklimi import ediyorum.
from sklearn.linear_model import LinearRegression

In [18]:
# MOdel nesnesini tanımlıyorum.
lmm = LinearRegression()

In [21]:
# BU model nesnesini kulanarak modeli fit et
model = lmm.fit(X,y)

In [22]:
# Bu modele burdan ulaşıyorum.
model.intercept_

array([2.93888937])

In [23]:
# Bağımsız değişkenlere ilişkin kat sayı değerlerini gözlemliyoruz.
model.coef_

array([[ 0.04576465,  0.18853002, -0.00103749]])

# tahmin

In [25]:
# Burda bir el yordamı ile hesaolama yaptım.
2.94 + 30 *0.04 + 10 * 0.19 - 40 * 0.001

5.999999999999999

In [37]:
# Şimdi aynı işlemi ben burda yeni çoklu veri tanımlayıp yapaçağım.
yeni_veri = [[30],[10],[40]]

In [38]:
import pandas as pd

In [39]:
# Yeni veriyi date frame formatında çağırma işlemini yaptım
yeni_veri = pd.DataFrame(yeni_veri).T

In [40]:
yeni_veri

0   1   2
0  30  10  40

In [41]:
# Şimdi tahmin ettirme işlemi yapaçağım.
model.predict(yeni_veri)

C:\Users\realb\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([[6.15562918]])

In [20]:
# Şimdi bu modelin hata kareler ortalamasına bakalım.
from sklearn.metrics import mean_squared_error

In [43]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [44]:
model.predict(X)[0:10]

array([[20.52397441],
       [12.33785482],
       [12.30767078],
       [17.59782951],
       [13.18867186],
       [12.47834763],
       [11.72975995],
       [12.12295317],
       [ 3.72734086],
       [12.55084872]])

In [46]:
# burdan hata karaler ortalamamızı buluruz.
# y bağılmı değişken sales değerlerimiz x değeri ise bizim tanımladığımız x değeri yani bağımsız değişkenlerimiz olarak ele alabiliriz.
MSE = mean_squared_error(y, model.predict(X))
MSE

2.784126314510936

In [21]:
# hata kareler ortalamasını almak için ise bu işlemi yapıyorum.

import numpy as np

In [54]:
RMSE = np.sqrt(MSE)
RMSE

1.6685701407225697

# Model Tuning (Model doğrulama)

In [8]:
X.head()

TV  radio  newspaper
0  230.1   37.8       69.2
1   44.5   39.3       45.1
2   17.2   45.9       69.3
3  151.5   41.3       58.5
4  180.8   10.8       58.4

In [9]:
y.head()

sales
0   22.1
1   10.4
2    9.3
3   18.5
4   12.9

In [10]:
# Sınama seti uygulayacağım fonksyonu çağırıyorum.
from sklearn.model_selection import train_test_split

In [12]:
# Şimdi burda yapaçağım veri setini bağımlı ve bağımsız olarak ayırma işlemini yapacağım
# Bu ayırma işlemini yüzde 20'ye yüzde 80 olarak tanımlıyorum ve bu işlemi bu şekilde olacak şekilde yapıyorum.
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.20, random_state = 99)

In [13]:
X_train.head()

TV  radio  newspaper
16    67.8   36.6      114.0
51   100.4    9.6        3.6
97   184.9   21.0       22.0
164  117.2   14.7        5.4
71   109.8   14.3       31.7

In [14]:
y_train.head()

sales
16    12.5
51    10.7
97    15.5
164   11.9
71    12.4

In [15]:
X_test.head()

TV  radio  newspaper
135  48.3   47.0        8.5
127  80.2    0.0        9.2
191  75.5   10.8        6.0
66   31.5   24.6        2.2
119  19.4   16.0       22.3

In [16]:
y_test.head()

sales
135   11.6
127    8.8
191    9.9
66     9.5
119    6.6

In [19]:
lmm = LinearRegression()
model = lmm.fit(X_train,y_train)


In [22]:
# Burda yaptığım işlem aslında benim yapmış olduğum modelde train hatamız olarak tanımlamış oluyorum.
# Burda x bağımlısız değişkenlerinin train işlemi yaprken y bağımlı değişkenine olan hatalarını hesaplamada kulanıyorum.
# Eğitim hatası

np.sqrt(mean_squared_error(y_train, model.predict(X_train)))

1.723682482265075

In [23]:
# Eğitim hatası varsa test hatasında vardır.
# test hatası hesaplamasını yapıyorum.

np.sqrt(mean_squared_error(y_test, model.predict(X_test)))

1.4312783138301646

In [26]:
# k-katlı cv hesaplama
# Bunu yapmaktaki amaçımız aslında şu train işleminde yapılan hata işlemini daha doğru şekıilde hesaplama yapmak için hesaplama yapıyorum.

from sklearn.model_selection import cross_val_score

In [28]:
# Train seti üzerinden on farklı hata hesaplaması yapılmış oldu
# Bu işlem şu şekilde olmuş oldu train seti on parçaya bölündü ve ve bu bölünme işleminden sonra dokuz tanesi ile test yapıldı ve o dışarda kalan bir tahmin edilmeye çalışıldı.
# Ve bu dokuza bir işlemini tarin özelinde yapmaya devam ediyoruz.

cross_val_score(model, X_train, y_train, cv=10, scoring="neg_mean_squared_error")

array([-2.1019073 , -2.48953197, -3.09704214, -2.34694216, -3.68175761,
       -1.8691401 , -3.18173007, -4.1927349 , -2.17128376, -8.03821974])

In [29]:
# Bu sonuçlar negatif ve ben bunun ortalama şekilinde alınmasını istiyorum bunu nasıl yaparım diye düşündüğüm zaman ise şu şekilde olmalıdır.
# cv ile elde edilmiş MSE değerimiz. Çapraz doğrulama ile elde edilmiş değer.

np.mean(-cross_val_score(model, X_train, y_train, cv=10, scoring="neg_mean_squared_error"))

3.3170289742341255

In [30]:
# RMSE değeri hesaplama işlemi yapmak istersek nasıl yapmalıyız.
np.sqrt(np.mean(-cross_val_score(model, X_train, y_train, cv=10, scoring="neg_mean_squared_error")))

1.8212712522395245

In [ ]:
"""
Buda önemli nokta şu siz eğitim veri setinizi çapraz doğrulama yapmadan değerlendirerseniz bizim öreneğimizdeki gibi 
1.723682482265075 şekilibde sonuç alırsınız ama eğer çapraz doğrulama işlemi yapar ve bu şekilde bir işlem yaparsabnız sonuç
1.8212712522395245 seklinde çıkar bu çapraz doğrulama işlemini size uygulamanızı özeniririm.
Peki bu işleme neden ihtiyaç duyduk bu işlem bize tek başına sadece test ve eğitim hatasını hesaplamadan daha doğru bir sonuç vermiş olur
bu yüzden bu işleme ihtiyaç duymaktayız.
"""